### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by neur1n** [CoreRC/Pavilion#7]
Hello. So when I tried to run the `BuildThirdParty.sh` script, it says "Please run this script from the plugin folder". I have tried to run it from several directory paths but it still did not work. Please provide more instructions. Thanks.

**Comment by zhaishengfu** [comment]
the same error

**Comment by ProfFan** [comment]
Sorry for the late reply. The script should be run in the `Plugins/PavilionPlugin` directory, and you need to create a folder called `Release` there, as shown in the script.
