### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zhaishengfu** [CoreRC/Pavilion#8]
home/dm/unrealproject/Pavilion/Plugins/PavilionPlugin/ThirdParty/Source/sdformat/src/urdf/urdf_parser/link.cpp: In function ‘bool urdf::exportGeometry(urdf::GeometrySharedPtr&, TiXmlElement*)’:
/home/dm/unrealproject/Pavilion/Plugins/PavilionPlugin/ThirdParty/Source/sdformat/src/urdf/urdf_parser/link.cpp:561:21: error: ‘SPHERE’ was not declared in this scope
   if (geom->type == SPHERE)
                     ^
/home/dm/unrealproject/Pavilion/Plugins/PavilionPlugin/ThirdParty/Source/sdformat/src/urdf/urdf_parser/link.cpp:565:26: error: ‘BOX’ was not declared in this scope
   else if (geom->type == BOX)
                          ^
/home/dm/unrealproject/Pavilion/Plugins/PavilionPlugin/ThirdParty/Source/sdformat/src/urdf/urdf_parser/link.cpp:569:26: error: ‘CYLINDER’ was not declared in this scope
   else if (geom->type == CYLINDER)
                          ^
/home/dm/unrealproject/Pavilion/Plugins/PavilionPlugin/ThirdParty/Source/sdformat/src/urdf/urdf_parser/link.cpp:573:26: error: ‘MESH’ was not declared in this scope

**Comment by zhaishengfu** [comment]
i solved this error by adding Geometry to them. but another error occured:
/usr/include/c++/5/bits/shared_ptr.h:458:50: error: ‘dynamic_cast’ not permitted with -fno-rtti
       if (_Tp* __p = dynamic_cast<_Tp*>(__r.get()))

**Comment by zhaishengfu** [comment]
i solved the above error. a new error of "install_name_tool " is not defined occured.  Dose your plugin can only be used under Mac? What about ubuntu system?

**Comment by zhaishengfu** [comment]
sorry, but i think this program can only run under mac, is it right? if so, please write clearly the platform, thank you

**Comment by zhaishengfu** [comment]
i see this can also run under ubuntu, so can you offer a tutorial on how to install under ubuntu 16.04?

**Comment by ProfFan** [comment]
This should not happen. P.S. my env is macOS 10.13 and ROS melodic.

**Comment by ProfFan** [comment]
You have to first install ROS and supporting libraries, in this case `urdfdom`.
